[workspace]
resolver = "2"
members = ["crates/*","app", "examples/simple_demo"]

[workspace.dependencies]
#Core und Window handeling
winit = { version = "0.29.4", default-features = false} #https://github.com/emilk/egui/blob/release-0.28.0/Cargo.toml
wgpu = { version = "0.20.0", default-features = true, features = [
    # Make the renderer `Sync` even on wasm32, because it makes the code simpler:
    "fragile-send-sync-non-atomic-wasm",
] }
pollster = "0.3"

#GUI
egui = "0.28.0" 
egui-winit = "0.28.0" 
egui-wgpu = "0.28.0" 
eframe = "0.28.0"

#Logging
log = "0.4"
env_logger = "0.11"

#Für die Buffer-Uploads
bytemuck = { version = "1.16", features = ["derive", "min_const_generics"] }

#Mathe
glam = "0.27"

#Zufall
rand = "0.8"
rand_distr = "0.4"

#Config laden
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"

#Benchmarks
criterion = "0.8.0"

#Background Image
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

pp_physics = { path = "./crates/physics" }
pp_render = { path = "./crates/render" }
pp_scenes = { path = "./crates/scenes" }
pp_gui =    { path = "./crates/gui" }
pp_app ={ path= "./app"}
pp_asssets = { path = "./assets" }