[package]
name = "pp_app"
version = "0.1.0"
edition = "2024"

[dependencies]
# own crates
pp_physics = { workspace = true }
pp_render = { workspace = true }
pp_scenes = { workspace = true }


# external tools
winit = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }
eframe = {workspace = true }
image = {workspace = true }